baseURL = "http://example.org/"
languageCode = "en-us"
title = "Stock2Shop"
theme = ["stock2shop_website", "s2s"]
[params]
  site_logo = "/images/stock2shop-logo.png"
  custom_css = ["css/custom.css", "css/custom2.css", "css/style.css"]

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[taxonomies]
  category = "categories"
  integration = "integrations"
  integration-doc = "integration-docs"
  tag = "tags"